version: '3.9'
services:
  postgres:
    image: postgres:17
    container_name: school-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=school_management_db
    volumes:
      - school_pgdata:/var/lib/postgresql/data

volumes:
  school_pgdata:
