// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5iaIKj3VFLMvZpWKa8Z6-xzQ_8T5Hy5Y',
    appId: '1:247311564576:web:ad6d5e28a32c867eda2145',
    messagingSenderId: '247311564576',
    projectId: 'bbu-school-management-system',
    authDomain: 'bbu-school-management-system.firebaseapp.com',
    storageBucket: 'bbu-school-management-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNO46RRxq3WrtTLqzhH9Dnw8CaQte8sKU',
    appId: '1:247311564576:android:54d5d0a09711d535da2145',
    messagingSenderId: '247311564576',
    projectId: 'bbu-school-management-system',
    storageBucket: 'bbu-school-management-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLCHm4csVVOM_KMNWo3TwGnbTB43Zra0Y',
    appId: '1:247311564576:ios:9d8e1d78464a721bda2145',
    messagingSenderId: '247311564576',
    projectId: 'bbu-school-management-system',
    storageBucket: 'bbu-school-management-system.firebasestorage.app',
    iosBundleId: 'com.keoleaphy.schoolmanagement',
  );
}
